import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <NavBar/>
        <div className="pt-24">
          <div className="w-full">
            <div className="min-h-screen bg-background dark:bg-black">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}