import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNavBar from "@/components/NavBar/ResponsiveNavBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ResponsiveNavBar />
        {children}
      </body>
    </html>
  );
}
