// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter from next/font
import "./globals.css";
import NavBarTest from "@/components/navBar/NavBarTest";
import Footer from "@/components/Footer"; // Assuming your Footer is in components/Footer.jsx

const inter = Inter({ subsets: ["latin"] }); // Initialize the Inter font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}> {/* Apply the font class here */}
      <body>
        <NavBarTest />
        <div className="pt-24">
          <div className="w-full">
            <div className="min-h-screen bg-background dark:bg-black">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}